# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  github-doodle = {
    pname = "github-doodle";
    version = "0258a9d2559ade48b44aad3c7833b9008536e1bd";
    src = fetchgit {
      url = "https://github.com/zhabinsky/github-doodle.git";
      rev = "0258a9d2559ade48b44aad3c7833b9008536e1bd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Val27/1yTfPaK8ZVBIPYGo8Hp2qo25z3R6m/zcHzwks=";
    };
  };
}
